name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build Debug
      run: dotnet build -c Debug --no-restore

    - name: Format # Must happen after a build so source generated files are available
      run: dotnet format --verify-no-changes --verbosity diagnostic --severity info

    - name: Test Debug
      run: dotnet test --no-build --verbosity normal

    - name: Build Release
      run: dotnet build -c Release --no-restore

    - name: Test Release
      run: dotnet test --no-build --verbosity normal

    - name: Nuget Push
      if: github.event_name == 'push'
      working-directory: pkg
      run: dotnet nuget push "*.nupkg" --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_TOKEN }} --skip-duplicate